const enStrings = {
  "unknownError": "Unknown error",
  "notice": "Notice",
  "close": "Close",
  "continues": "Continue",
  "setting": "Setting",
  "cancel": "Cancel",
  "noNetTitle": "No internet connection",
  "noNetContent": "No internet connection, please try again later",
  "retry": "Retry",
  "allow": "Allow",
  "weatherForYourTrip": "Weather for Your Trip",
  "weatherForPlace": "Weather for Place",
  "yourPlanedTrip": "Your Planned Trip",
  "weatherForFamousPlace": "Weather for Famous Place",
  "exploreNearbyPlaces": "Explore Nearby Places",
  "chooseKindPlace": "Choose kind of place ...",
  "yourStartLocation": "Your start location",
  "yourSearchLocation": "Find location",
  "yourDestination": "Your destination",
  "departureTime": "Departure time",
  "date": "Date",
  "time": "Time",
  "averageSpeed": "Average speed is 40mph ( 64 kmh )",
  "checkWeather": "Check Weather ",
  "checkPlace": "Check Place ",
  "yourTrip": "Your Trip ",
  "weatherTimeline": "Weather Timeline",
  "weatherForecast": "Weather Forecast",
  "wind": "Wind",
  "windGust": "Wind gust",
  "humidity": "Humidity",
  "dewPoint": "Dew point",
  "skyCover": "Sky cover",
  "barometer": "Barometer",
  "visibility": "Visibility",
  "precipitation": "Precipitation",
  "errorLocation00": "Enable device location permission to update  temperature and weather condition",
  "errorLocation01": "Please enable location services",
  "errorLocation02":
      "Update temperature and weather conditions of your location by allowing access to your precise location",
  "errorLocation03":
      "Update temperature and weather conditions of your location by allowing access to your precise location",
  "errorLocation04": "Please check your GPS settings and allow the app to access your location",
  "errorEmptyAdd": "Please enter full information about the origin and destination",
  "errorEmptyAdd2": "Please enter full information",
  "errorEmptyRoute": "No route found",
  "errorEmptyWeather": "No weather information, please try again later",
  "locationWarn": "Enable device location permission to update temperature and weather condition",
  "errorLoadAds": "The function is not ready, please try again in a moment",
  "rateUs": "Rate us",
  "privacy": "Privacy policy",
  "termOfCondition": "Term of condition",
  "shareApp": "Share app",
  "contactUs": "Contact us",
  "language": "Language",
  "moreApp": "More app",
  "shareMessage":
      "Install to update outside temperature, humidity, weekly weather forecast and AQI to protect yourself and your family",
  "hintRate": "Write your comment",
  "rate": "Rate",
  "joinNow": "Join now",
  "settingPremiumTitle": "Unlimited trips with\nPro route planner",
  "subTitle": "Ready to become\nVIP member",
  "restoreSuccessful": "Restore successful",
  "restore": "Restore",
  "descriptionSub":
      "This subscription automatically renews after 3-days trial period for @priceOfMonth/week and @priceOfYear/year, you can cancel it anytime. Payment will be charged to your Google Play account at the confirmation of purchase. Subscription automatically renews unless it is canceled at least 24 hours before the end of the current period. You can manage and cancel your subscriptions by going to your account settings on the GooglePlay after purchase. Any unused part or time-span of a free trial period will be forfeited, as soon as you purchase a subscriptions.",
  "free3Days": "Free 3 days trial",
  "subHint1": "Weather forecast for each road",
  "subHint2": "No limitations on trip length",
  "subHint3": "Plan your trip with AI ChatBot Assistant",
  "subHint4": "No ads, Cancel anytime",
  "perWeek": "per Week",
  "perYear": "per Year",
  "bestOffer": "Best choice",
  "kindOfPlace": "Kind of Place",
  "evCharger": "EV charger",
  "gasStation": "Gas Station",
  "hotel": "Hotel & Hostel",
  "restaurantAndBar": "Restaurant & Bars",
  "campSite": "Camp Sites",
  "touristAttraction": "Tourist Attraction",
  "hospital": "Hospital",
  "pharmacy": "Pharmacy",
  "fellLike": "Feel like",
  "history": "History",
  "favorite": "Your Favorite",
  "search": "Search",
};
