const viStrings = {
  "unknownError": "Lỗi không xác định",
  "notice": "Thông báo",
  "close": "Đóng",
  "continues": "Tiếp tục",
  "setting": "Cài đặt",
  "cancel": "Huỷ",
  "noNetTitle": "Không có kết nối mạng",
  "noNetContent": "Không có kết nối mạng, vui lòng thử lại sau",
  "retry": "Thử lại",
  "allow": "Cho phép",
  "weatherForYourTrip": "Thời tiết cho chuyến đi của bạn",
  "weatherForPlace": "Thời tiết cho địa điểm",
  "weatherForFamousPlace": "Thời tiết địa điểm nổi tiếng",
  "yourPlanedTrip": "Chuyến đi theo kế hoạch",
  "exploreNearbyPlaces": "Khám phá các địa điểm lân cận",
  "chooseKindPlace": "Chọn loại địa điểm ...",
  "yourStartLocation": "Vị trí bắt đầu của bạn",
  "yourSearchLocation": "Vị trí tìm kiếm",
  "yourDestination": "Đích đến của bạn",
  "departureTime": "Giờ khởi hành",
  "date": "Ngày",
  "time": "Giờ",
  "averageSpeed": "Tốc độ trung bình là 40mph (64 kmh)",
  "checkWeather": "Kiểm tra thời tiết",
  "checkPlace": "Kiểm tra địa điểm",
  "yourTrip": "Chuyến đi của bạn",
  "weatherTimeline": "Dòng thời tiết",
  "weatherForecast": "Dự báo thời tiết",
  "wind": "Gió",
  "windGust": "Gió giật",
  "humidity": "Độ ẩm",
  "barometer": "Áp suất",
  "dewPoint": "Điểm sương",
  "skyCover": "Mây",
  "visibility": "Tầm nhìn",
  "precipitation": "Khả năng có mưa",
  "errorLocation00": "Bật quyền truy cập vị trí thiết bị để cập nhật nhiệt độ và điều kiện thời tiết",
  "errorLocation01": "Vui lòng bật dịch vụ vị trí",
  "errorLocation02":
      "Cập nhật nhiệt độ và điều kiện thời tiết của vị trí của bạn bằng cách cho phép truy cập vào vị trí chính xác của bạn",
  "errorLocation03":
      "Cập nhật nhiệt độ và điều kiện thời tiết của vị trí của bạn bằng cách cho phép truy cập vào vị trí chính xác của bạn",
  "errorLocation04": "Vui lòng kiểm tra cài đặt GPS và cho phép ứng dụng truy cập vị trí của bạn",
  "errorEmptyAdd": "Vui lòng nhập đầy đủ thông tin về điểm xuất phát, điểm đến",
  "errorEmptyAdd2": "Vui lòng nhập đầy đủ thông tin",
  "errorEmptyRoute": "Không tìm thấy cung đường nào",
  "errorEmptyWeather": "Không có thông tin thời tiết, vui lòng thử lại sau",
  "locationWarn": "Bật quyền truy cập vị trí thiết bị để cập nhật nhiệt độ và điều kiện thời tiết",
  "errorLoadAds": "Chức năng chưa sẵn sàng, vui lòng thử lại sau giây lát",
  "rateUs": "Đánh giá",
  "privacy": "Chính sách bảo mật",
  "termOfCondition": "Điều khoản sử dụng",
  "shareApp": "Chia sẻ",
  "contactUs": "Liên hệ",
  "language": "Ngôn ngữ",
  "moreApp": "Ứng dụng khác",
  "shareMessage":
      "Tải app để theo dõi nhiệt độ ngoài trời, độ ẩm, cập nhật tình hình thời tiết và chỉ số ô nhiễm không khí để bảo vệ bản thân và gia đình bạn",
  "hintRate": "Bình luận của bạn",
  "rate": "Đánh giá",
  "joinNow": "Tham gia",
  "settingPremiumTitle": "Các chuyến đi không giới hạn\nvới lộ trình chuyên nghiệp",
  "subTitle": "Các chuyến đi không giới hạn với\nCông cụ lập lộ trình chuyên nghiệp",
  "restoreSuccessful": "Khôi phục thành công",
  "restore": "Khôi phục",
  "descriptionSub":
      "Đăng ký này tự động gia hạn sau thời gian dùng thử 3 ngày cho @priceOfMonth/tháng và @priceOfYear/năm, bạn có thể hủy đăng ký bất cứ lúc nào. Thanh toán sẽ được tính vào tài khoản Google Play của bạn khi xác nhận mua hàng. Đăng ký tự động gia hạn trừ khi nó bị hủy ít nhất 24 giờ trước khi kết thúc giai đoạn hiện tại. Bạn có thể quản lý và hủy đăng ký của mình bằng cách truy cập cài đặt tài khoản của bạn trên GooglePlay sau khi mua. Mọi phần hoặc khoảng thời gian chưa sử dụng của giai đoạn dùng thử miễn phí sẽ bị hủy bỏ, ngay sau khi bạn mua đăng ký.",
  "free3Days": "Miễn phí 3 ngày dùng thử",
  "subHint1": "•   Loại bỏ quảng cáo",
  "subHint2": "•   Chuyến đi không giới hạn",
  "subHint3": "•   Mở khóa tất cả tính năng",
  "subHint4": "•   Tự động tái tạo",
  "perWeek": "mỗi tuần",
  "perYear": "mỗi năm",
  "bestOffer": "Best choice",
  "kindOfPlace": "Loại địa điểm",
  "evCharger": "Trạm sạc điện",
  "gasStation": "Trạm xăng",
  "hotel": "Khách sạn & Nhà nghỉ",
  "restaurantAndBar": "Cửa hàng & Quán bar",
  "campSite": "Điểm cắm trại",
  "touristAttraction": "Điểm du lịch",
  "hospital": "Bệnh viện",
  "pharmacy": "Hiệu thuốc",
  "fellLike": "Cảm giác",
  "favorite": "Ưu thích",
  "history": "Lịch sử",
  "search": "Tìm kiếm",
};
